name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: assignment-api

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: 'latest'

    - name: 'Authenticate with GCP'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_B64 }}'

    - name: 'Set GCP project'
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.GKE_REGION }}-docker.pkg.dev --quiet

    - name: Build Docker image
      env:
        AR_REGISTRY: ${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo
      run: |
        docker build -t $AR_REGISTRY/$IMAGE:${{ github.sha }} .

    - name: Push Docker image
      env:
        AR_REGISTRY: ${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo
      run: |
        docker push $AR_REGISTRY/$IMAGE:${{ github.sha }}
      
    - name: Debug Information
      if: failure()
      run: |
        echo "Debug information:"
        gcloud config list
        gcloud auth list
        docker images
        echo "Artifact Registry repositories:"
        gcloud artifacts repositories list --location=${{ env.GKE_REGION }} || echo "Failed to list repositories"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GCP_REGION }}
        TF_VAR_vpc_name: "assignment-vpc"
        TF_VAR_subnet_name: "assignment-subnet"
        TF_VAR_subnet_cidr: "10.0.0.0/24"
        TF_VAR_cluster_name: "assignment-cluster"
        TF_VAR_node_pool_name: "assignment-node-pool"
        TF_VAR_node_count: "1"
        TF_VAR_machine_type: "e2-medium"
        TF_VAR_service_account_id: "assignment-sa"
        TF_VAR_k8s_namespace: "assignment"
        TF_VAR_iam_roles_to_grant: '["roles/container.developer", "roles/storage.objectViewer"]'
        TF_VAR_open_ports: '["80", "443", "3000"]'
        TF_VAR_container_image: "assignment-api"
        TF_VAR_container_version: ${{ github.sha }}
        TF_VAR_replicas: "2"

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GCP_REGION }}
        TF_VAR_vpc_name: "assignment-vpc"
        TF_VAR_subnet_name: "assignment-subnet"
        TF_VAR_subnet_cidr: "10.0.0.0/24"
        TF_VAR_cluster_name: "assignment-cluster"
        TF_VAR_node_pool_name: "assignment-node-pool"
        TF_VAR_node_count: "1"
        TF_VAR_machine_type: "e2-medium"
        TF_VAR_service_account_id: "assignment-sa"
        TF_VAR_k8s_namespace: "assignment"
        TF_VAR_iam_roles_to_grant: '["roles/container.developer", "roles/storage.objectViewer"]'
        TF_VAR_open_ports: '["80", "443", "3000"]'
        TF_VAR_container_image: "assignment-api"
        TF_VAR_container_version: ${{ github.sha }}
        TF_VAR_replicas: "2"

    - name: Verify GKE Cluster Access
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }}
        kubectl get nodes

    - name: Verify API
      run: |
        LOAD_BALANCER_IP=$(kubectl get service assignment-service -n assignment -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        for i in {1..30}; do
          response=$(curl -s -o /dev/null -w "%{http_code}" http://$LOAD_BALANCER_IP:3000)
          if [ $response -eq 200 ]; then
            echo "API is accessible"
            exit 0
          fi
          echo "Waiting for API to become accessible... Attempt $i"
          sleep 10
        done
        echo "API did not become accessible within the timeout period"
        exit 1