name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_REGION: ${{ secrets.GCP_REGION }}
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_key.json

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: 'latest'
        install_components: 'gke-gcloud-auth-plugin'

    - name: 'Decode and authenticate with GCP'
      run: |
        echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 --decode > /tmp/gcp_key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GCP_REGION }}
        TF_VAR_vpc_name: "assignment-vpc"
        TF_VAR_subnet_name: "assignment-subnet"
        TF_VAR_subnet_cidr: "10.0.0.0/24"
        TF_VAR_cluster_name: "assignment-cluster"
        TF_VAR_node_pool_name: "assignment-node-pool"
        TF_VAR_node_count: "1"
        TF_VAR_machine_type: "e2-medium"
        TF_VAR_service_account_id: "assignment-sa"
        TF_VAR_k8s_namespace: "assignment"
        TF_VAR_iam_roles_to_grant: '["roles/container.developer", "roles/storage.objectViewer"]'
        TF_VAR_open_ports: '["80", "443", "3000"]'
        TF_VAR_container_image: "assignment-api"
        TF_VAR_container_version: ${{ github.sha }}
        TF_VAR_replicas: "2"        

